// SPDX-License-Identifier: MIT
#ifndef M5_HAL_I2S_I2S_HPP_
#define M5_HAL_I2S_I2S_HPP_

#include "../bus/bus.hpp"
#include "../bus/bus_view.hpp"
#include "../bus/hal_backend.hpp"
#include "../bus/managed_facade.hpp"
#include "../bus/registry.hpp"
#include "../data.hpp"
#include "../data/stream.hpp"
#include "../types.hpp"

#include <stddef.h>
#include <stdint.h>
#include <atomic>
#include <memory>
#include <new>

/*!
  @namespace m5::hal::v2::i2s
  @brief I2S bus, per-channel accessors, and stream-style sample I/O.

  ## Getting a bus (entry point)

  Buses are obtained from a `Hal` facade instance — `M5_Hal` (the local
  device) or a user-constructed remote `Hal` — never by naming a concrete
  backend type yourself. Remote instances are connected via
  `Hal::connect(endpoint)`; see m5_hal.hpp.

  @code
  m5hal::i2s::BusConfig cfg{m5hal::i2s::Bclk{12}, m5hal::i2s::Ws{0}, m5hal::i2s::Dout{2}};
  auto bus = m5hal::M5_Hal.I2S.acquire(cfg);  // result_t<shared_ptr<IBus>>
  if (!bus) {
      // handle bus.error()
  }
  @endcode

  Note: `i2s::BusConfig` is an alias supplied by the active build variant —
  this abstract header defines only the `IBusConfig` base and the pin tags.
  Include the v2 entry header (`<M5HAL_v2.hpp>`) and the alias resolves
  to the variant's concrete config type.

  Acquiring the same wiring twice returns the same instance (identity
  acquire; see spec/design/bus_accessor.md). The concrete backend is
  selected by the build variant through the config type. Direct
  construction (`i2s::Bus bus; bus.init(cfg);`) remains the advanced path.
 */
namespace m5::hal::v2::i2s {

/// I2S is a DMA-driven continuous stream with no transaction boundaries like I2C/SPI.
/// The API mirrors uart (write / read / writableBytes / readableBytes). TX (playback)
/// and RX (recording) are independent DMA paths on one controller, so a full-duplex bus
/// can write and read at the same time; the Philips standard slot format is fixed. Pins
/// drive the direction: DOUT enables TX, DIN enables RX, both enable full duplex.

/*!
  @brief Independent TX / RX channels, used to key the per-channel bus locks.

  I2S splits the bus lock into independent TX and RX mutexes (the uart model),
  so one owner can write (TX) while another reads (RX) on a full-duplex bus.
  `Tx` / `Rx` are bit flags; `TxRx` is the composite that the bundled accessor
  and the base `lock()` take.
 */
enum class Channel : uint8_t {
    None = 0,
    Tx   = 1u << 0,
    Rx   = 1u << 1,
    TxRx = (1u << 0) | (1u << 1),
};
using channel_t = Channel;

constexpr Channel operator|(Channel lhs, Channel rhs)
{
    return static_cast<Channel>(static_cast<uint8_t>(lhs) | static_cast<uint8_t>(rhs));
}

constexpr Channel operator&(Channel lhs, Channel rhs)
{
    return static_cast<Channel>(static_cast<uint8_t>(lhs) & static_cast<uint8_t>(rhs));
}

constexpr bool hasChannel(Channel value, Channel bit)
{
    return (static_cast<uint8_t>(value) & static_cast<uint8_t>(bit)) == static_cast<uint8_t>(bit);
}

/*!
  @brief Strong-typed I2S pins. Like i2c::Scl / spi::Clk, these tags keep a
  swapped wiring from compiling. BCLK / WS are the shared clocks; DOUT enables
  TX, DIN enables RX, and both direction pins are part of the bus identity.
  The ctor below covers the common TX form (BCLK / WS / DOUT); DIN and MCLK
  are set by field assignment afterwards.
 */
struct Bclk {
    constexpr explicit Bclk(types::gpio_number_t pin) : value{pin}
    {
    }
    types::gpio_number_t value;
};

/*! @brief Strong-typed WS (word select / LRCLK) pin. See @ref Bclk. */
struct Ws {
    constexpr explicit Ws(types::gpio_number_t pin) : value{pin}
    {
    }
    types::gpio_number_t value;
};

/*! @brief Strong-typed DOUT (data out, TX) pin. See @ref Bclk. */
struct Dout {
    constexpr explicit Dout(types::gpio_number_t pin) : value{pin}
    {
    }
    types::gpio_number_t value;
};

/*! @brief Strong-typed DIN (data in, RX) pin. See @ref Bclk. */
struct Din {
    constexpr explicit Din(types::gpio_number_t pin) : value{pin}
    {
    }
    types::gpio_number_t value;
};

/*!
  @brief Standard-I2S wiring and backend configuration.

  Both master and slave configurations require non-negative BCLK and WS pins,
  plus at least one direction pin (DOUT for TX and/or DIN for RX). `init()` /
  typed `acquire()` reject an incomplete configuration with `INVALID_ARGUMENT`;
  MCLK remains optional. PDM is a separate bus/API and is not selected through
  this configuration.
 */
struct IBusConfig : public bus::IBusConfig {
    /*!
      @brief Clock direction (which side of the link drives BCLK / WS).

      `Master` generates the clocks (the default, e.g. driving a DAC or
      capturing from a microphone that follows our clock); `Slave` consumes
      clocks generated by a peer. Role is not part of the bus identity (it is
      not wiring), so it is set by field assignment, not the pin ctor.
     */
    enum class Role : uint8_t {
        Master = 0,
        Slave  = 1,
    };

    types::gpio_number_t pin_bclk = -1;  ///< Required standard-I2S bit clock pin.
    types::gpio_number_t pin_ws   = -1;  ///< Required standard-I2S word-select/LRCLK pin.
    types::gpio_number_t pin_dout = -1;  ///< TX (playback) data out; -1 = no TX channel.
    types::gpio_number_t pin_din  = -1;  ///< RX (recording) data in; -1 = no RX channel.
    types::gpio_number_t pin_mclk = -1;  ///< External MCLK output for codecs that require it; -1 = disabled.
    size_t tx_buffer_size = 8192;  ///< Approximate TX DMA buffer size; the backend rounds to descriptor granularity.
    size_t rx_buffer_size = 8192;  ///< Approximate RX DMA buffer size; the backend rounds to descriptor granularity.
    Role role             = Role::Master;  ///< Clock direction; not part of the bus identity.

    constexpr IBusConfig(void) : bus::IBusConfig{types::bus_kind_t::I2S}
    {
    }
    /*!
      @brief Tag-typed core pins for the common TX form (BCLK / WS / DOUT).
      DIN (RX/full-duplex) and MCLK are set by field assignment afterwards.
     */
    constexpr IBusConfig(Bclk bclk, Ws ws, Dout dout)
        : bus::IBusConfig{types::bus_kind_t::I2S}, pin_bclk{bclk.value}, pin_ws{ws.value}, pin_dout{dout.value}
    {
    }
    /*! @brief Tag-typed core pins for the RX-only form (BCLK / WS / DIN). */
    constexpr IBusConfig(Bclk bclk, Ws ws, Din din)
        : bus::IBusConfig{types::bus_kind_t::I2S}, pin_bclk{bclk.value}, pin_ws{ws.value}, pin_din{din.value}
    {
    }
    /*! @brief Tag-typed core pins for full-duplex (BCLK / WS / DOUT / DIN). */
    constexpr IBusConfig(Bclk bclk, Ws ws, Dout dout, Din din)
        : bus::IBusConfig{types::bus_kind_t::I2S},
          pin_bclk{bclk.value},
          pin_ws{ws.value},
          pin_dout{dout.value},
          pin_din{din.value}
    {
    }
};

/*! @brief Variant-independent portable I2S bus configuration. */
using BusConfig = IBusConfig;

/*!
  @brief Pin + intent acquire request for the unified BusView surface.

  I2S currently uses static backend selection through `acquire(BusConfig)`;
  the logical acquire overload exists on `BusView` for API parity with I2C/SPI
  and reports `NOT_IMPLEMENTED` until I2S grows a controller/capability
  allocation policy.
 */
struct LogicalBusConfig {
    types::gpio_number_t pin_bclk = -1;
    types::gpio_number_t pin_ws   = -1;
    types::gpio_number_t pin_dout = -1;
    types::gpio_number_t pin_din  = -1;
    types::AllocationIntent intent{};

    constexpr LogicalBusConfig(void) = default;
    /*! @brief Tag-typed core pins (BCLK / WS / DOUT). DIN is set afterwards. */
    constexpr LogicalBusConfig(Bclk bclk, Ws ws, Dout dout, types::AllocationIntent in = {})
        : pin_bclk{bclk.value}, pin_ws{ws.value}, pin_dout{dout.value}, intent{in}
    {
    }
    /*! @brief Tag-typed core pins for RX-only (BCLK / WS / DIN). */
    constexpr LogicalBusConfig(Bclk bclk, Ws ws, Din din, types::AllocationIntent in = {})
        : pin_bclk{bclk.value}, pin_ws{ws.value}, pin_din{din.value}, intent{in}
    {
    }
    /*! @brief Tag-typed core pins for full-duplex (BCLK / WS / DOUT / DIN). */
    constexpr LogicalBusConfig(Bclk bclk, Ws ws, Dout dout, Din din, types::AllocationIntent in = {})
        : pin_bclk{bclk.value}, pin_ws{ws.value}, pin_dout{dout.value}, pin_din{din.value}, intent{in}
    {
    }
};

struct AccessConfig : public bus::IAccessConfig {
    uint32_t sample_rate_hz   = 44100;
    uint32_t write_timeout_ms = 1000;  ///< Max wait for DMA free space during write, in ms; 0 = non-blocking.
    uint32_t read_timeout_ms  = 1000;  ///< Max wait for DMA captured data during read, in ms; 0 = non-blocking.
    uint8_t bits_per_sample   = 16;    ///< Currently only 16 is supported.
    uint8_t channels          = 2;     ///< Logical PCM shape: 1 = mono / 2 = interleaved stereo.

    constexpr AccessConfig(void) : bus::IAccessConfig{types::bus_kind_t::I2S}
    {
    }
};

struct IBus;

/*!
  @brief TX-side accessor; locks only the TX channel.

  TX and RX are independent channel locks, so one owner can write while another
  reads on a full-duplex bus. An Access is non-nesting and establishes the TX
  backend operation once. Write sugar borrows an active Access or opens a
  temporary one. Accessors must not be shared between threads. `setConfig`
  fails with `INVALID_STATE` while an Access is active.
 */
struct TxAccessor : public bus::IAccessor, public data::StreamWriter {
    TxAccessor(IBus& bus, const AccessConfig& access_config);
    /*! @brief Co-owning construction from an acquired shared bus (`M5_Hal.I2S.acquire(cfg)`). */
    TxAccessor(std::shared_ptr<IBus> bus, const AccessConfig& access_config);

    /*! @name Unbound construction + typed bind (gate: `beginAccess` on TX channel). @{ */
    TxAccessor(void) : _context{makeOperationContext(AccessConfig{})}
    {
    }
    explicit TxAccessor(const AccessConfig& access_config) : _context{makeOperationContext(access_config)}
    {
    }
    /*! @brief Bind (or rebind) to an I2S bus; rejected while the TX window is open. */
    [[nodiscard]] m5::hal::v2::result_t<void> bind(IBus& bus);
    /*! @} */

    const AccessConfig& getConfig(void) const override
    {
        return _context.config;
    }
    IBus& getBus(void) const;

    [[nodiscard]] result_t<void> setConfig(const AccessConfig& cfg);
    [[nodiscard]] result_t<void> beginAccess(uint32_t timeout_ms = types::TIMEOUT_FOREVER);
    [[nodiscard]] result_t<void> endAccess(uint32_t timeout_ms = 1000);
    bool inAccess(void) const
    {
        return _inOperationAccess();
    }
    result_t<bus::TransferStatus> getLastTransferStatus(void) const;

    result_t<size_t> write(data::ConstDataSpan src_bytes) override;
    result_t<size_t> write(data::Source& src, size_t len);
    result_t<size_t> write(const uint8_t* src, size_t len);

    /// Bytes that can be accepted by write() right now without blocking (DMA buffer free space).
    result_t<size_t> writableBytes(void);

protected:
    friend struct Accessor;
    bus::OperationContext<AccessConfig> _context;

private:
    result_t<size_t> writeInCurrentAccess(data::Source& src, size_t len);
    void recordTransferResult(const result_t<size_t>& result, size_t requested);

    bus::TransferStatus _last_transfer_status{};
    uint32_t _next_transfer_id = 0;
};

/*!
  @brief RX-side accessor; locks only the RX channel.

  The mirror of `TxAccessor`: independent RX channel lock and a non-nesting
  Access that establishes the RX backend operation once. There is no
  `readUntil` sugar (it is line-oriented and meaningless on a continuous I2S
  stream). Accessors must not be shared between threads.
 */
struct RxAccessor : public bus::IAccessor, public data::StreamReader {
    RxAccessor(IBus& bus, const AccessConfig& access_config);
    /*! @brief Co-owning construction from an acquired shared bus (`M5_Hal.I2S.acquire(cfg)`). */
    RxAccessor(std::shared_ptr<IBus> bus, const AccessConfig& access_config);

    /*! @name Unbound construction + typed bind (gate: `beginAccess` on RX channel). @{ */
    RxAccessor(void) : _context{makeOperationContext(AccessConfig{})}
    {
    }
    explicit RxAccessor(const AccessConfig& access_config) : _context{makeOperationContext(access_config)}
    {
    }
    /*! @brief Bind (or rebind) to an I2S bus; rejected while the RX window is open. */
    [[nodiscard]] m5::hal::v2::result_t<void> bind(IBus& bus);
    /*! @} */

    const AccessConfig& getConfig(void) const override
    {
        return _context.config;
    }
    IBus& getBus(void) const;

    [[nodiscard]] result_t<void> setConfig(const AccessConfig& cfg);
    [[nodiscard]] result_t<void> beginAccess(uint32_t timeout_ms = types::TIMEOUT_FOREVER);
    [[nodiscard]] result_t<void> endAccess(uint32_t timeout_ms = 1000);
    bool inAccess(void) const
    {
        return _inOperationAccess();
    }
    result_t<bus::TransferStatus> getLastTransferStatus(void) const;

    result_t<size_t> read(data::DataSpan dst_bytes) override;
    result_t<size_t> read(data::Sink& dst, size_t len);
    result_t<size_t> read(uint8_t* dst, size_t len);

    /// Bytes that can be read() right now without blocking (DMA captured data).
    result_t<size_t> readableBytes(void) override;

protected:
    friend struct Accessor;
    bus::OperationContext<AccessConfig> _context;

private:
    result_t<size_t> readInCurrentAccess(data::Sink& dst, size_t len);
    void recordTransferResult(const result_t<size_t>& result, size_t requested);

    bus::TransferStatus _last_transfer_status{};
    uint32_t _next_transfer_id = 0;
};

/*!
  @brief Convenience facade bundling one TX and one RX accessor.

  `beginAccess` opens both channels in TX -> RX order, spending the remaining
  timeout budget on the second lock (an infinite budget stays infinite); if the
  RX lock fails the already-acquired TX lock is rolled back. The split accessors
  are the primary API — the facade keeps full-duplex code short. Like UART's
  bundle there is no `readUntil` (RX has none on a continuous stream).
 */
struct Accessor {
    Accessor(IBus& bus, const AccessConfig& access_config);
    /*!
      @brief Co-owning construction from an acquired shared bus. Both channels share
      ownership of the bus (`M5_Hal.I2S.acquire(cfg)`).
     */
    Accessor(std::shared_ptr<IBus> bus, const AccessConfig& access_config);

    /*! @name Unbound construction + typed bind (delegates to both channels). @{ */
    Accessor(void) = default;
    explicit Accessor(const AccessConfig& access_config) : _tx{access_config}, _rx{access_config}
    {
    }
    /*! @brief Bind (or rebind) both channel accessors; rejected while either window is open. */
    [[nodiscard]] result_t<void> bind(IBus& bus);
    /*! @} */

    const AccessConfig& getConfig(void) const
    {
        return _tx.getConfig();
    }
    IBus& getBus(void) const;

    TxAccessor& tx(void)
    {
        return _tx;
    }
    const TxAccessor& tx(void) const
    {
        return _tx;
    }
    RxAccessor& rx(void)
    {
        return _rx;
    }
    const RxAccessor& rx(void) const
    {
        return _rx;
    }

    [[nodiscard]] result_t<void> setConfig(const AccessConfig& cfg);
    [[nodiscard]] result_t<void> beginAccess(uint32_t timeout_ms = types::TIMEOUT_FOREVER);
    [[nodiscard]] result_t<void> endAccess(uint32_t timeout_ms = 1000);
    bool inAccess(void) const
    {
        return _combined_active || _tx.inAccess() || _rx.inAccess();
    }

    result_t<size_t> write(data::ConstDataSpan src_bytes);
    result_t<size_t> write(data::Source& src, size_t len);
    result_t<size_t> write(const uint8_t* src, size_t len);
    result_t<size_t> writableBytes(void);

    result_t<size_t> read(data::DataSpan dst_bytes);
    result_t<size_t> read(data::Sink& dst, size_t len);
    result_t<size_t> read(uint8_t* dst, size_t len);
    result_t<bus::TransferTotals> transfer(data::Source& src, size_t tx_len, data::Sink& dst, size_t rx_len);
    result_t<bus::TransferTotals> transfer(data::ConstDataSpan src_bytes, data::DataSpan dst_bytes);
    result_t<bus::TransferStatus> getLastTransferStatus(void) const;
    result_t<size_t> readableBytes(void);

protected:
    TxAccessor _tx;
    RxAccessor _rx;

private:
    void adoptTransferStatus(const result_t<bus::TransferStatus>& before, const result_t<bus::TransferStatus>& after);
    void recordTransferResult(const result_t<bus::TransferTotals>& result, size_t requested_tx, size_t requested_rx);

    bus::TransferStatus _last_transfer_status{};
    uint32_t _next_transfer_id = 0;
    bool _combined_active      = false;
};

struct IBus : public bus::IBus {
    const IBusConfig& getConfig(void) const override
    {
        return _config;
    }

    /// Returns the byte count accepted within write_timeout_ms; a short return is normal.
    /// Underrun is not an error: the DMA outputs silence and resumes on the next write.
    result_t<size_t> write(bus::OperationContext<AccessConfig>& context, data::Source* src, size_t len);
    result_t<size_t> writableBytes(bus::OperationContext<AccessConfig>& context);

    /// Returns the byte count captured within read_timeout_ms; a short return is normal.
    /// Overrun (a slow reader) drops the oldest DMA data; it is not an error here.
    result_t<size_t> read(bus::OperationContext<AccessConfig>& context, data::Sink* dst, size_t len);
    /*!
      @brief Transfer bytes in both independent I2S directions.

      The contract is direction-independent concurrent progress: TX consumes
      up to `tx_len` bytes while RX produces up to `rx_len` bytes. The default
      implementation approximates this for local backends by running `write`
      first and then `read`; a backend with true full-duplex DMA may override
      it. If either step fails, the error is returned immediately, and bytes
      from the earlier step may already have moved.
     */
    result_t<bus::TransferTotals> transfer(bus::OperationContext<AccessConfig>& tx_context,
                                           bus::OperationContext<AccessConfig>& rx_context, data::Source* src,
                                           size_t tx_len, data::Sink* dst, size_t rx_len);
    result_t<size_t> readableBytes(bus::OperationContext<AccessConfig>& context);

    result_t<void> beginOperation(bus::OperationContext<AccessConfig>& context);
    result_t<void> endOperation(bus::OperationContext<AccessConfig>& context);

protected:
    virtual result_t<void> beginOperationBackend(bus::OperationContext<AccessConfig>& context);
    virtual result_t<void> endOperationBackend(bus::OperationContext<AccessConfig>& context);
    virtual result_t<size_t> writeBackend(bus::OperationContext<AccessConfig>& context, data::Source* src, size_t len);
    virtual result_t<size_t> writableBytesBackend(bus::OperationContext<AccessConfig>& context);
    virtual result_t<size_t> readBackend(bus::OperationContext<AccessConfig>& context, data::Sink* dst, size_t len);
    virtual result_t<bus::TransferTotals> transferBackend(bus::OperationContext<AccessConfig>& tx_context,
                                                          bus::OperationContext<AccessConfig>& rx_context,
                                                          data::Source* src, size_t tx_len, data::Sink* dst,
                                                          size_t rx_len);
    virtual result_t<size_t> readableBytesBackend(bus::OperationContext<AccessConfig>& context);

    static result_t<void> beginOperationOn(IBus& backend, bus::OperationContext<AccessConfig>& context)
    {
        return backend.beginOperationBackend(context);
    }
    static result_t<void> endOperationOn(IBus& backend, bus::OperationContext<AccessConfig>& context)
    {
        return backend.endOperationBackend(context);
    }
    static result_t<size_t> writeOn(IBus& backend, bus::OperationContext<AccessConfig>& context, data::Source* src,
                                    size_t len)
    {
        return backend.writeBackend(context, src, len);
    }
    static result_t<size_t> writableBytesOn(IBus& backend, bus::OperationContext<AccessConfig>& context)
    {
        return backend.writableBytesBackend(context);
    }
    static result_t<size_t> readOn(IBus& backend, bus::OperationContext<AccessConfig>& context, data::Sink* dst,
                                   size_t len)
    {
        return backend.readBackend(context, dst, len);
    }
    static result_t<bus::TransferTotals> transferOn(IBus& backend, bus::OperationContext<AccessConfig>& tx_context,
                                                    bus::OperationContext<AccessConfig>& rx_context, data::Source* src,
                                                    size_t tx_len, data::Sink* dst, size_t rx_len)
    {
        return backend.transferBackend(tx_context, rx_context, src, tx_len, dst, rx_len);
    }
    static result_t<size_t> readableBytesOn(IBus& backend, bus::OperationContext<AccessConfig>& context)
    {
        return backend.readableBytesBackend(context);
    }
    bus::OperationSlot* operationSlot(bus::OperationContext<AccessConfig>& context);
    const bus::OperationSlot* operationSlot(const bus::OperationContext<AccessConfig>& context) const;
    bus::IAccessor* operationOwner(bus::OperationContext<AccessConfig>& context);

    friend struct TxAccessor;
    friend struct RxAccessor;
    result_t<void> acquireAccessLock(bus::IAccessor& owner, uint32_t timeout_ms = types::TIMEOUT_FOREVER) override;
    result_t<void> releaseAccessLock(bus::IAccessor& owner) override;
    virtual result_t<void> lockChannel(bus::IAccessor& owner, Channel ch, uint32_t timeout_ms = types::TIMEOUT_FOREVER);
    virtual result_t<void> unlockChannel(bus::IAccessor& owner, Channel ch);
    result_t<void> tryAcquireCloseBarrier(void) override;
    result_t<void> releaseCloseBarrier(void) override;

    IBusConfig _config;
    // I2S splits the bus lock into independent TX / RX channels, so it carries
    // one runtime::Mutex per channel (the composite txrx lock takes both, TX
    // first); the base Bus mutex stays unused here. Lock semantics per channel
    // match the common Access lock: wait up to timeout_ms, TIMEOUT_ERROR on expiry,
    // non-recursive, task context only.
    runtime::Mutex _tx_mutex;
    runtime::Mutex _rx_mutex;
    bus::IAccessor* _tx_lock_owner = nullptr;
    bus::IAccessor* _rx_lock_owner = nullptr;
    std::atomic<void*> _tx_lock_task{nullptr};
    std::atomic<void*> _rx_lock_task{nullptr};
    bus::OperationSlot _tx_operation_slot;
    bus::OperationSlot _rx_operation_slot;
};

//-------------------------------------------------------------------------
// bind() is defined below the concrete IBus: at the accessors' point of
// declaration the kind IBus is still an incomplete type, so the
// derived-to-base conversion _bindBus needs is not visible yet.
inline m5::hal::v2::result_t<void> TxAccessor::bind(IBus& bus)
{
    if (inAccess()) {
        return m5::stl::make_unexpected(error::error_t::INVALID_STATE);
    }
    _bindBus(bus);
    return {};
}
inline m5::hal::v2::result_t<void> RxAccessor::bind(IBus& bus)
{
    if (inAccess()) {
        return m5::stl::make_unexpected(error::error_t::INVALID_STATE);
    }
    _bindBus(bus);
    return {};
}
inline m5::hal::v2::result_t<void> Accessor::bind(IBus& bus)
{
    if (inAccess()) {
        return m5::stl::make_unexpected(error::error_t::INVALID_STATE);
    }
    (void)_tx.bind(bus);
    (void)_rx.bind(bus);
    return {};
}

template <class Policy>
struct NativeProvider;

struct Bus;  // the facade, defined just below

/*!
  @brief Per-kind Traits for the shared `bus::FacadeCore` and BusView.

  I2S's `Bus` shares the base spine (backend ownership + `init` +
  `close` + the query mirror). Its plain `BusView` uses the same traits for
  portable acquire identity: concrete kind `IBus`, the bus-level config base,
  the public `BusType`, kind tag, and the 4-pin
  (BCLK/WS/DOUT/DIN) identity projection. I2S has no intent / hot-swap
  surface, so the master-only Traits members are intentionally absent. `Bus` is
  forward-declared at namespace scope so `BusType` names the public `i2s::Bus`,
  not a nested type.
 */
struct BusTraits {
    using IBus             = i2s::IBus;
    using IBusConfig       = i2s::IBusConfig;
    using LogicalBusConfig = i2s::LogicalBusConfig;
    using BusType          = Bus;
    template <class Policy>
    using NativeProvider = i2s::NativeProvider<Policy>;

    static constexpr types::bus_kind_t KIND = types::bus_kind_t::I2S;
    /*! @brief I2S uses the static-backend policy: `BusView::hardwareInUse()`
               is always 0 (see spec/design/bus_accessor.md §static-backend
               policy). */
    static constexpr bool MANAGED_ALLOCATION = false;

    static bus::ResourceKey identityFromConfig(const IBusConfig& cfg)
    {
        return bus::ResourceKey::fromPins(KIND, {cfg.pin_bclk, cfg.pin_ws, cfg.pin_dout, cfg.pin_din});
    }
    static bus::ResourceKey identityFromLogical(const LogicalBusConfig& req)
    {
        return bus::ResourceKey::fromPins(KIND, {req.pin_bclk, req.pin_ws, req.pin_dout, req.pin_din});
    }
    static bool configCompatible(const IBusConfig& current, const IBusConfig& requested)
    {
        return current.pin_bclk == requested.pin_bclk && current.pin_ws == requested.pin_ws &&
               current.pin_dout == requested.pin_dout && current.pin_din == requested.pin_din &&
               current.pin_mclk == requested.pin_mclk && current.tx_buffer_size == requested.tx_buffer_size &&
               current.rx_buffer_size == requested.rx_buffer_size && current.role == requested.role;
    }
};

/*!
  @brief Runtime facade for an I2S bus (the unsuffixed i2s::Bus).

  All of the backend spine -- the `unique_ptr`-held backend, `init`, `close`,
  and the lock-free backend-query mirror -- lives in
  `bus::FacadeCore<BusTraits>`. This derived type adds only the I2S data-path
  forwards (write / read / writableBytes / readableBytes). The TX / RX channel
  locks (lock / unlock / lockChannel / unlockChannel and the two channel
  mutexes) are INHERITED from i2s::IBus and stay on THIS facade -- the accessors
  contend on the facade's channel mutexes, the backend's stay dormant. So the
  2-mutex channel model needs no special handling here: only the data path is
  delegated. Mirrors the uart::Bus design without the intent /
  hot-swap extensions.
 */
struct Bus : public bus::FacadeCore<BusTraits> {
    [[nodiscard]] result_t<void> init(const IBusConfig& config);

protected:
    result_t<void> beginOperationBackend(bus::OperationContext<AccessConfig>& context) override
    {
        return forwardBackend([&](IBus& b) { return beginOperationOn(b, context); });
    }

    result_t<void> endOperationBackend(bus::OperationContext<AccessConfig>& context) override
    {
        return forwardBackend([&](IBus& b) { return endOperationOn(b, context); });
    }

    result_t<size_t> writeBackend(bus::OperationContext<AccessConfig>& context, data::Source* src, size_t len) override
    {
        return forwardBackend([&](IBus& b) { return writeOn(b, context, src, len); });
    }

    result_t<size_t> writableBytesBackend(bus::OperationContext<AccessConfig>& context) override
    {
        return forwardBackend([&](IBus& b) { return writableBytesOn(b, context); });
    }

    result_t<size_t> readBackend(bus::OperationContext<AccessConfig>& context, data::Sink* dst, size_t len) override
    {
        return forwardBackend([&](IBus& b) { return readOn(b, context, dst, len); });
    }

    result_t<bus::TransferTotals> transferBackend(bus::OperationContext<AccessConfig>& tx_context,
                                                  bus::OperationContext<AccessConfig>& rx_context, data::Source* src,
                                                  size_t tx_len, data::Sink* dst, size_t rx_len) override
    {
        return forwardBackend([&](IBus& b) { return transferOn(b, tx_context, rx_context, src, tx_len, dst, rx_len); });
    }

    result_t<size_t> readableBytesBackend(bus::OperationContext<AccessConfig>& context) override
    {
        return forwardBackend([&](IBus& b) { return readableBytesOn(b, context); });
    }
};

/*!
  @brief Typed I2S view delegating registry access to the HAL backend.

  Shares the acquire / logical-acquire / commit / close spine with every
  other kind through `bus::BusViewCore<BusTraits>` (see bus/bus_view.hpp);
  this derived type adds only the I2S-specific `createBusConfig()` pin
  overloads. Parity with i2c::BusView and spi::BusView: I2S buses are
  interned by the HAL backend's registry keyed by physical wiring (BCLK,
  WS, DOUT, DIN pins). acquire(cfg) returns the bus for those pins, creating
  it (the facade + the backend selected by cfg's type, via Bus::init) on the
  first call and sharing it on later calls for the same wiring. BCLK and WS
  are mandatory; DOUT / DIN default to -1 for TX-only or RX-only wiring.

  The public view uses the static-backend policy: `commitBuses()` exists and is
  a no-op, while logical acquire reports `NOT_IMPLEMENTED` until I2S grows a
  controller/capability allocation policy.
 */
class BusView : public bus::BusViewCore<BusTraits> {
public:
    using bus::BusViewCore<BusTraits>::BusViewCore;

    LogicalBusConfig createBusConfig(Bclk bclk, Ws ws, Dout dout, types::AllocationIntent intent = {}) const
    {
        return {bclk, ws, dout, intent};
    }
    LogicalBusConfig createBusConfig(Bclk bclk, Ws ws, Din din, types::AllocationIntent intent = {}) const
    {
        return {bclk, ws, din, intent};
    }
    LogicalBusConfig createBusConfig(Bclk bclk, Ws ws, Dout dout, Din din, types::AllocationIntent intent = {}) const
    {
        return {bclk, ws, dout, din, intent};
    }
};

/*!
  @brief Non-owning I2S bus group; retained for code that uses the
         slot-based publish/lookup table directly.
 */
using BusGroup = bus::BusGroup<IBus>;

}  // namespace m5::hal::v2::i2s

#endif
