// SPDX-License-Identifier: MIT
#ifndef M5_HAL_I2S_I2S_HPP_
#define M5_HAL_I2S_I2S_HPP_

#include "../bus/bus.hpp"
#include "../bus/hal_backend.hpp"
#include "../bus/managed_facade.hpp"
#include "../bus/registry.hpp"
#include "../data.hpp"
#include "../data/stream.hpp"
#include "../types.hpp"

#include <stddef.h>
#include <stdint.h>
#include <memory>
#include <new>
#include <type_traits>

/*!
  @namespace m5::hal::v2::i2s
  @brief I2S bus, per-channel accessors, and stream-style sample I/O.

  ## Getting a bus (entry point)

  Buses are obtained from a `Hal` facade instance — `M5_Hal` (the local
  device) or a user-constructed remote `Hal` — never by naming a concrete
  backend type yourself. Remote instances are connected via
  `Hal::connect(endpoint)`; see m5_hal.hpp.

  @code
  m5hal::i2s::BusConfig cfg{m5hal::i2s::Bclk{12}, m5hal::i2s::Ws{0}, m5hal::i2s::Dout{2}};
  auto bus = m5hal::M5_Hal.I2S.acquire(cfg);  // result_t<shared_ptr<IBus>>
  if (!bus) {
      // handle bus.error()
  }
  @endcode

  Note: `i2s::BusConfig` is an alias supplied by the active build variant —
  this abstract header defines only the `IBusConfig` base and the pin tags.
  Include the v2 entry header (`<M5HAL_v2.hpp>`) and the alias resolves
  to the variant's concrete config type.

  Acquiring the same wiring twice returns the same instance (identity
  acquire; see spec/design/bus_accessor.md). The concrete backend is
  selected by the build variant through the config type. Direct
  construction (`i2s::Bus bus; bus.init(cfg);`) remains the advanced path.
 */
namespace m5::hal::v2::i2s {

/// I2S is a DMA-driven continuous stream with no transaction boundaries like I2C/SPI.
/// The API mirrors uart (write / read / writableBytes / readableBytes). TX (playback)
/// and RX (recording) are independent DMA paths on one controller, so a full-duplex bus
/// can write and read at the same time; the Philips standard slot format is fixed. Pins
/// drive the direction: DOUT enables TX, DIN enables RX, both enable full duplex.

/*!
  @brief Independent TX / RX channels, used to key the per-channel bus locks.

  I2S splits the bus lock into independent TX and RX mutexes (the uart model),
  so one owner can write (TX) while another reads (RX) on a full-duplex bus.
  `Tx` / `Rx` are bit flags; `TxRx` is the composite that the bundled accessor
  and the base `lock()` take.
 */
enum class Channel : uint8_t {
    None = 0,
    Tx   = 1u << 0,
    Rx   = 1u << 1,
    TxRx = (1u << 0) | (1u << 1),
};
using channel_t = Channel;

constexpr Channel operator|(Channel lhs, Channel rhs)
{
    return static_cast<Channel>(static_cast<uint8_t>(lhs) | static_cast<uint8_t>(rhs));
}

constexpr Channel operator&(Channel lhs, Channel rhs)
{
    return static_cast<Channel>(static_cast<uint8_t>(lhs) & static_cast<uint8_t>(rhs));
}

constexpr bool hasChannel(Channel value, Channel bit)
{
    return (static_cast<uint8_t>(value) & static_cast<uint8_t>(bit)) == static_cast<uint8_t>(bit);
}

/*!
  @brief Strong-typed I2S pins. Like i2c::Scl / spi::Clk, these tags keep a
  swapped wiring from compiling. BCLK / WS are the shared clocks; DOUT enables
  TX, DIN enables RX, and both direction pins are part of the bus identity.
  The ctor below covers the common TX form (BCLK / WS / DOUT); DIN and MCLK
  are set by field assignment afterwards.
 */
struct Bclk {
    constexpr explicit Bclk(types::gpio_number_t pin) : value{pin}
    {
    }
    types::gpio_number_t value;
};

/*! @brief Strong-typed WS (word select / LRCLK) pin. See @ref Bclk. */
struct Ws {
    constexpr explicit Ws(types::gpio_number_t pin) : value{pin}
    {
    }
    types::gpio_number_t value;
};

/*! @brief Strong-typed DOUT (data out, TX) pin. See @ref Bclk. */
struct Dout {
    constexpr explicit Dout(types::gpio_number_t pin) : value{pin}
    {
    }
    types::gpio_number_t value;
};

/*! @brief Strong-typed DIN (data in, RX) pin. See @ref Bclk. */
struct Din {
    constexpr explicit Din(types::gpio_number_t pin) : value{pin}
    {
    }
    types::gpio_number_t value;
};

struct IBusConfig : public bus::IBusConfig {
    /*!
      @brief Clock direction (which side of the link drives BCLK / WS).

      `Master` generates the clocks (the default, e.g. driving a DAC or
      capturing from a microphone that follows our clock); `Slave` consumes
      clocks generated by a peer. Role is not part of the bus identity (it is
      not wiring), so it is set by field assignment, not the pin ctor.
     */
    enum class Role : uint8_t {
        Master = 0,
        Slave  = 1,
    };

    types::gpio_number_t pin_bclk = -1;
    types::gpio_number_t pin_ws   = -1;
    types::gpio_number_t pin_dout = -1;  ///< TX (playback) data out; -1 = no TX channel.
    types::gpio_number_t pin_din  = -1;  ///< RX (recording) data in; -1 = no RX channel.
    types::gpio_number_t pin_mclk = -1;  ///< External MCLK output for codecs that require it; -1 = disabled.
    size_t tx_buffer_size = 8192;  ///< Approximate TX DMA buffer size; the backend rounds to descriptor granularity.
    size_t rx_buffer_size = 8192;  ///< Approximate RX DMA buffer size; the backend rounds to descriptor granularity.
    Role role             = Role::Master;  ///< Clock direction; not part of the bus identity.

    constexpr IBusConfig(void) : bus::IBusConfig{types::bus_kind_t::I2S}
    {
    }
    /*!
      @brief Tag-typed core pins for the common TX form (BCLK / WS / DOUT).
      DIN (RX/full-duplex) and MCLK are set by field assignment afterwards.
     */
    constexpr IBusConfig(Bclk bclk, Ws ws, Dout dout)
        : bus::IBusConfig{types::bus_kind_t::I2S}, pin_bclk{bclk.value}, pin_ws{ws.value}, pin_dout{dout.value}
    {
    }
    /*! @brief Tag-typed core pins for the RX-only form (BCLK / WS / DIN). */
    constexpr IBusConfig(Bclk bclk, Ws ws, Din din)
        : bus::IBusConfig{types::bus_kind_t::I2S}, pin_bclk{bclk.value}, pin_ws{ws.value}, pin_din{din.value}
    {
    }
    /*! @brief Tag-typed core pins for full-duplex (BCLK / WS / DOUT / DIN). */
    constexpr IBusConfig(Bclk bclk, Ws ws, Dout dout, Din din)
        : bus::IBusConfig{types::bus_kind_t::I2S},
          pin_bclk{bclk.value},
          pin_ws{ws.value},
          pin_dout{dout.value},
          pin_din{din.value}
    {
    }
};

/*!
  @brief Pin + intent acquire request for the unified BusView surface.

  I2S currently uses static backend selection through `acquire(BusConfig)`;
  the logical acquire overload exists on `BusView` for API parity with I2C/SPI
  and reports `NOT_IMPLEMENTED` until I2S grows a controller/capability
  allocation policy.
 */
struct LogicalBusConfig {
    types::gpio_number_t pin_bclk = -1;
    types::gpio_number_t pin_ws   = -1;
    types::gpio_number_t pin_dout = -1;
    types::gpio_number_t pin_din  = -1;
    types::AllocationIntent intent{};

    constexpr LogicalBusConfig(void) = default;
    /*! @brief Tag-typed core pins (BCLK / WS / DOUT). DIN is set afterwards. */
    constexpr LogicalBusConfig(Bclk bclk, Ws ws, Dout dout, types::AllocationIntent in = {})
        : pin_bclk{bclk.value}, pin_ws{ws.value}, pin_dout{dout.value}, intent{in}
    {
    }
    /*! @brief Tag-typed core pins for RX-only (BCLK / WS / DIN). */
    constexpr LogicalBusConfig(Bclk bclk, Ws ws, Din din, types::AllocationIntent in = {})
        : pin_bclk{bclk.value}, pin_ws{ws.value}, pin_din{din.value}, intent{in}
    {
    }
    /*! @brief Tag-typed core pins for full-duplex (BCLK / WS / DOUT / DIN). */
    constexpr LogicalBusConfig(Bclk bclk, Ws ws, Dout dout, Din din, types::AllocationIntent in = {})
        : pin_bclk{bclk.value}, pin_ws{ws.value}, pin_dout{dout.value}, pin_din{din.value}, intent{in}
    {
    }
};

struct AccessConfig : public bus::IAccessConfig {
    uint32_t sample_rate_hz   = 44100;
    uint32_t write_timeout_ms = 1000;  ///< Max wait for DMA free space during write, in ms; 0 = non-blocking.
    uint32_t read_timeout_ms  = 1000;  ///< Max wait for DMA captured data during read, in ms; 0 = non-blocking.
    uint8_t bits_per_sample   = 16;    ///< Currently only 16 is supported.
    uint8_t channels          = 2;     ///< 1 = mono / 2 = stereo.

    constexpr AccessConfig(void) : bus::IAccessConfig{types::bus_kind_t::I2S}
    {
    }
};

struct IBus;

/*!
  @brief TX-side accessor; locks only the TX channel.

  TX and RX are independent channel locks, so one owner can write while another
  reads on a full-duplex bus. `beginAccess` / `endAccess` (TX channel) nest
  through a depth counter, and the write sugars open the window themselves.

  An I2S transaction is a TX channel exclusion scope plus byte-count
  aggregation; it has no physical CS or bus-occupancy side effect. Accessors
  must not be shared between threads. The transaction depth is only for
  same-owner reentry, while sharing the Bus through separate accessors is
  supported. `setConfig` fails with `INVALID_STATE` while an access window is
  open.
 */
struct TxAccessor : public bus::IAccessor, public data::StreamWriter {
    TxAccessor(IBus& bus, const AccessConfig& access_config);
    /*! @brief Co-owning construction from a borrowed bus (`M5_Hal.I2S.acquire(cfg)`). */
    TxAccessor(std::shared_ptr<IBus> bus, const AccessConfig& access_config);

    /*! @name Unbound construction + typed bind (gate: `beginAccess` on TX channel). @{ */
    TxAccessor(void) = default;
    explicit TxAccessor(const AccessConfig& access_config) : _access_config{access_config}
    {
    }
    /*! @brief Bind (or rebind) to an I2S bus; rejected while the TX window is open. */
    m5::hal::v2::result_t<void> bind(IBus& bus);
    /*! @} */

    const AccessConfig& getConfig(void) const override
    {
        return _access_config;
    }
    IBus& getBus(void) const;

    result_t<void> setConfig(const AccessConfig& cfg);
    result_t<void> beginAccess(uint32_t timeout_ms = types::TIMEOUT_FOREVER);
    result_t<void> endAccess(void);
    bool inAccess(void) const
    {
        return _tx_access_depth > 0;
    }

    result_t<void> beginTransaction(uint32_t timeout_ms = types::TIMEOUT_FOREVER);
    result_t<bus::TransferTotals> endTransaction(void);
    bool inTransaction(void) const
    {
        return _tx_txn_depth > 0;
    }

    result_t<size_t> write(data::ConstDataSpan src_bytes) override;
    result_t<size_t> write(data::Source& src, size_t len);
    result_t<size_t> write(const uint8_t* src, size_t len);

    /// Bytes that can be accepted by write() right now without blocking (DMA buffer free space).
    result_t<size_t> writableBytes(void);

protected:
    AccessConfig _access_config;

private:
    uint32_t _tx_access_depth = 0;
    uint32_t _tx_txn_depth    = 0;
    bus::TransferTotals _tx_txn_totals;
};

/*!
  @brief RX-side accessor; locks only the RX channel.

  The mirror of `TxAccessor`: independent RX channel lock, depth counter via
  `beginAccess` / `endAccess` (RX channel), and `setConfig` fails with
  `INVALID_STATE` while an access window is open. There is no `readUntil`
  sugar (it is line-oriented and meaningless on a continuous I2S stream).

  An I2S transaction is an RX channel exclusion scope plus byte-count
  aggregation; it has no physical CS or bus-occupancy side effect. Accessors
  must not be shared between threads. The transaction depth is only for
  same-owner reentry, while sharing the Bus through separate accessors is
  supported.
 */
struct RxAccessor : public bus::IAccessor, public data::StreamReader {
    RxAccessor(IBus& bus, const AccessConfig& access_config);
    /*! @brief Co-owning construction from a borrowed bus (`M5_Hal.I2S.acquire(cfg)`). */
    RxAccessor(std::shared_ptr<IBus> bus, const AccessConfig& access_config);

    /*! @name Unbound construction + typed bind (gate: `beginAccess` on RX channel). @{ */
    RxAccessor(void) = default;
    explicit RxAccessor(const AccessConfig& access_config) : _access_config{access_config}
    {
    }
    /*! @brief Bind (or rebind) to an I2S bus; rejected while the RX window is open. */
    m5::hal::v2::result_t<void> bind(IBus& bus);
    /*! @} */

    const AccessConfig& getConfig(void) const override
    {
        return _access_config;
    }
    IBus& getBus(void) const;

    result_t<void> setConfig(const AccessConfig& cfg);
    result_t<void> beginAccess(uint32_t timeout_ms = types::TIMEOUT_FOREVER);
    result_t<void> endAccess(void);
    bool inAccess(void) const
    {
        return _rx_access_depth > 0;
    }

    result_t<void> beginTransaction(uint32_t timeout_ms = types::TIMEOUT_FOREVER);
    result_t<bus::TransferTotals> endTransaction(void);
    bool inTransaction(void) const
    {
        return _rx_txn_depth > 0;
    }

    result_t<size_t> read(data::DataSpan dst_bytes) override;
    result_t<size_t> read(data::Sink& dst, size_t len);
    result_t<size_t> read(uint8_t* dst, size_t len);

    /// Bytes that can be read() right now without blocking (DMA captured data).
    result_t<size_t> readableBytes(void) override;

protected:
    AccessConfig _access_config;

private:
    uint32_t _rx_access_depth = 0;
    uint32_t _rx_txn_depth    = 0;
    bus::TransferTotals _rx_txn_totals;
};

/*!
  @brief Convenience facade bundling one TX and one RX accessor.

  `beginAccess` opens both channels in TX -> RX order, spending the remaining
  timeout budget on the second lock (an infinite budget stays infinite); if the
  RX lock fails the already-acquired TX lock is rolled back. The split accessors
  are the primary API — the facade keeps full-duplex code short. Like UART's
  bundle there is no `readUntil` (RX has none on a continuous stream).
 */
struct Accessor {
    Accessor(IBus& bus, const AccessConfig& access_config);
    /*!
      @brief Co-owning construction from a borrowed bus. Both channels share
      ownership of the bus (`M5_Hal.I2S.acquire(cfg)`).
     */
    Accessor(std::shared_ptr<IBus> bus, const AccessConfig& access_config);

    /*! @name Unbound construction + typed bind (delegates to both channels). @{ */
    Accessor(void) = default;
    explicit Accessor(const AccessConfig& access_config) : _tx{access_config}, _rx{access_config}
    {
    }
    /*! @brief Bind (or rebind) both channel accessors; rejected while either window is open. */
    result_t<void> bind(IBus& bus);
    /*! @} */

    const AccessConfig& getConfig(void) const
    {
        return _tx.getConfig();
    }
    IBus& getBus(void) const;

    TxAccessor& tx(void)
    {
        return _tx;
    }
    const TxAccessor& tx(void) const
    {
        return _tx;
    }
    RxAccessor& rx(void)
    {
        return _rx;
    }
    const RxAccessor& rx(void) const
    {
        return _rx;
    }

    result_t<void> setConfig(const AccessConfig& cfg);
    result_t<void> beginAccess(uint32_t timeout_ms = types::TIMEOUT_FOREVER);
    result_t<void> endAccess(void);
    bool inAccess(void) const
    {
        return _tx.inAccess() || _rx.inAccess();
    }

    result_t<size_t> write(data::ConstDataSpan src_bytes);
    result_t<size_t> write(data::Source& src, size_t len);
    result_t<size_t> write(const uint8_t* src, size_t len);
    result_t<size_t> writableBytes(void);

    result_t<size_t> read(data::DataSpan dst_bytes);
    result_t<size_t> read(data::Sink& dst, size_t len);
    result_t<size_t> read(uint8_t* dst, size_t len);
    result_t<bus::TransferTotals> transfer(data::Source& src, size_t tx_len, data::Sink& dst, size_t rx_len);
    result_t<bus::TransferTotals> transfer(data::ConstDataSpan src_bytes, data::DataSpan dst_bytes);
    result_t<size_t> readableBytes(void);

protected:
    TxAccessor _tx;
    RxAccessor _rx;
};

struct IBus : public bus::IBus {
    const IBusConfig& getConfig(void) const override
    {
        return _config;
    }

    /// Returns the byte count accepted within write_timeout_ms; a short return is normal.
    /// Underrun is not an error: the DMA outputs silence and resumes on the next write.
    virtual result_t<size_t> write(bus::IAccessor* owner, const AccessConfig& cfg, data::Source* src, size_t len);
    virtual result_t<size_t> writableBytes(bus::IAccessor* owner, const AccessConfig& cfg);

    /// Returns the byte count captured within read_timeout_ms; a short return is normal.
    /// Overrun (a slow reader) drops the oldest DMA data; it is not an error here.
    virtual result_t<size_t> read(bus::IAccessor* owner, const AccessConfig& cfg, data::Sink* dst, size_t len);
    /*!
      @brief Transfer bytes in both independent I2S directions.

      The contract is direction-independent concurrent progress: TX consumes
      up to `tx_len` bytes while RX produces up to `rx_len` bytes. The default
      implementation approximates this for local backends by running `write`
      first and then `read`; a backend with true full-duplex DMA may override
      it. If either step fails, the error is returned immediately, and bytes
      from the earlier step may already have moved.
     */
    virtual result_t<bus::TransferTotals> transfer(bus::IAccessor* owner, const AccessConfig& cfg, data::Source* src,
                                                   size_t tx_len, data::Sink* dst, size_t rx_len);
    virtual result_t<size_t> readableBytes(bus::IAccessor* owner, const AccessConfig& cfg);

    result_t<void> lock(bus::IAccessor* owner, uint32_t timeout_ms = types::TIMEOUT_FOREVER) override;
    result_t<void> unlock(bus::IAccessor* owner) override;
    virtual result_t<void> lockChannel(bus::IAccessor* owner, Channel ch, uint32_t timeout_ms = types::TIMEOUT_FOREVER);
    virtual result_t<void> unlockChannel(bus::IAccessor* owner, Channel ch);

protected:
    IBusConfig _config;
    // I2S splits the bus lock into independent TX / RX channels, so it carries
    // one runtime::Mutex per channel (the composite txrx lock takes both, TX
    // first); the base Bus mutex stays unused here. Lock semantics per channel
    // match Bus::lock: wait up to timeout_ms, TIMEOUT_ERROR on expiry,
    // non-recursive, task context only.
    runtime::Mutex _tx_mutex;
    runtime::Mutex _rx_mutex;
    bus::IAccessor* _tx_lock_owner = nullptr;
    bus::IAccessor* _rx_lock_owner = nullptr;
};

//-------------------------------------------------------------------------
// bind() is defined below the concrete IBus: at the accessors' point of
// declaration the kind IBus is still an incomplete type, so the
// derived-to-base conversion _bindBus needs is not visible yet.
inline m5::hal::v2::result_t<void> TxAccessor::bind(IBus& bus)
{
    if (inAccess()) {
        return m5::stl::make_unexpected(error::error_t::INVALID_STATE);
    }
    _bindBus(bus);
    return {};
}
inline m5::hal::v2::result_t<void> RxAccessor::bind(IBus& bus)
{
    if (inAccess()) {
        return m5::stl::make_unexpected(error::error_t::INVALID_STATE);
    }
    _bindBus(bus);
    return {};
}
inline m5::hal::v2::result_t<void> Accessor::bind(IBus& bus)
{
    if (inAccess()) {
        return m5::stl::make_unexpected(error::error_t::INVALID_STATE);
    }
    (void)_tx.bind(bus);
    (void)_rx.bind(bus);
    return {};
}

/*!
  @brief Maps a variant BusConfig_<variant> to its backend Bus_<variant>.

  Undefined primary on purpose: passing a config type without a
  specialization to Bus::init is a compile error. Each variant header
  specializes this next to its Bus_<variant>.
 */
template <class CfgT>
struct BackendFor;

struct Bus;  // the facade, defined just below

/*!
  @brief Per-kind Traits for the shared `bus::FacadeCore` and BusView.

  I2S's `Bus` shares the phase-1/2 spine (backend ownership + `init` +
  `release` + the query mirror). Its plain `BusView` uses the same traits for
  typed acquire identity: concrete kind `IBus`, the bus-level config base, the
  variant selector (`FacadeCore`), the public `BusType`, kind tag, and the 4-pin
  (BCLK/WS/DOUT/DIN) identity projection. I2S has no phase-3 intent / hot-swap
  surface, so the master-only Traits members are intentionally absent. `Bus` is
  forward-declared at namespace scope so `BusType` names the public `i2s::Bus`,
  not a nested type.
 */
struct BusTraits {
    using IBus             = i2s::IBus;
    using IBusConfig       = i2s::IBusConfig;
    using LogicalBusConfig = i2s::LogicalBusConfig;
    using BusType          = Bus;
    template <class CfgT>
    using BackendFor = i2s::BackendFor<CfgT>;

    static constexpr types::bus_kind_t KIND = types::bus_kind_t::I2S;

    static bus::IdentityKey identityFromConfig(const IBusConfig& cfg)
    {
        return bus::IdentityKey::fromPins({cfg.pin_bclk, cfg.pin_ws, cfg.pin_dout, cfg.pin_din});
    }
    static bus::IdentityKey identityFromLogical(const LogicalBusConfig& req)
    {
        return bus::IdentityKey::fromPins({req.pin_bclk, req.pin_ws, req.pin_dout, req.pin_din});
    }
    static bool configCompatible(const IBusConfig& current, const IBusConfig& requested)
    {
        return current.pin_bclk == requested.pin_bclk && current.pin_ws == requested.pin_ws &&
               current.pin_dout == requested.pin_dout && current.pin_din == requested.pin_din &&
               current.pin_mclk == requested.pin_mclk && current.tx_buffer_size == requested.tx_buffer_size &&
               current.rx_buffer_size == requested.rx_buffer_size && current.role == requested.role;
    }
};

/*!
  @brief Runtime facade for an I2S bus (the unsuffixed i2s::Bus).

  All of the backend spine -- the `unique_ptr`-held backend, `init`, `release`,
  and the lock-free backend-query mirror -- lives in
  `bus::FacadeCore<BusTraits>`. This derived type adds only the I2S data-path
  forwards (write / read / writableBytes / readableBytes). The TX / RX channel
  locks (lock / unlock / lockChannel / unlockChannel and the two channel
  mutexes) are INHERITED from i2s::IBus and stay on THIS facade -- the accessors
  contend on the facade's channel mutexes, the backend's stay dormant. So the
  2-mutex channel model needs no special handling here: only the data path is
  delegated. Mirrors the uart::Bus design (ADR 034) without the phase-3 intent /
  hot-swap extensions.
 */
struct Bus : public bus::FacadeCore<BusTraits> {
    result_t<size_t> write(bus::IAccessor* owner, const AccessConfig& cfg, data::Source* src, size_t len) override
    {
        return forwardBackend([&](IBus& b) { return b.write(owner, cfg, src, len); });
    }

    result_t<size_t> writableBytes(bus::IAccessor* owner, const AccessConfig& cfg) override
    {
        return forwardBackend([&](IBus& b) { return b.writableBytes(owner, cfg); });
    }

    result_t<size_t> read(bus::IAccessor* owner, const AccessConfig& cfg, data::Sink* dst, size_t len) override
    {
        return forwardBackend([&](IBus& b) { return b.read(owner, cfg, dst, len); });
    }

    result_t<bus::TransferTotals> transfer(bus::IAccessor* owner, const AccessConfig& cfg, data::Source* src,
                                           size_t tx_len, data::Sink* dst, size_t rx_len) override
    {
        return forwardBackend([&](IBus& b) { return b.transfer(owner, cfg, src, tx_len, dst, rx_len); });
    }

    result_t<size_t> readableBytes(bus::IAccessor* owner, const AccessConfig& cfg) override
    {
        return forwardBackend([&](IBus& b) { return b.readableBytes(owner, cfg); });
    }
};

/*!
  @brief Typed I2S view delegating registry access to the HAL backend.

  ADR 034 phase 2 parity with i2c::BusView and spi::BusView: I2S buses are
  interned by the HAL backend's registry keyed by physical wiring (BCLK,
  WS, DOUT, DIN pins). acquire(cfg) returns the bus for those pins, creating
  it (the facade + the backend selected by cfg's type, via Bus::init) on the
  first call and sharing it on later calls for the same wiring. BCLK and WS
  are mandatory; DOUT / DIN default to -1 for TX-only or RX-only wiring.

  The public view uses the static-backend policy: `commitBuses()` exists and is
  a no-op, while logical acquire reports `NOT_IMPLEMENTED` until I2S grows a
  controller/capability allocation policy.
 */
class BusView {
public:
    BusView() : _backend{nullptr}
    {
    }
    explicit BusView(bus::IHalBackend* backend) : _backend{backend}
    {
    }
    BusView(const BusView&)            = delete;
    BusView& operator=(const BusView&) = delete;

    void setBackend(bus::IHalBackend* backend)
    {
        _backend = backend;
    }

    template <class CfgT>
    result_t<std::shared_ptr<IBus>> acquire(const CfgT& cfg)
    {
        static_assert(std::is_base_of<IBusConfig, CfgT>::value,
                      "BusView::acquire expects a BusConfig of this bus kind");
        if (_backend == nullptr) {
            return m5::stl::make_unexpected(error::error_t::NOT_CONNECTED);
        }
        bus::IdentityKey id = BusTraits::identityFromConfig(cfg);
        if (!id.valid()) {
            return m5::stl::make_unexpected(error::error_t::INVALID_ARGUMENT);
        }
        {
            auto r = _backend->acquireBusTyped(types::bus_kind_t::I2S, id, cfg);
            if (r.has_value()) {
                return std::static_pointer_cast<IBus>(r.value());
            }
            if (r.error() != error::error_t::NOT_IMPLEMENTED) {
                return m5::stl::make_unexpected(r.error());
            }
        }
        if (auto existing = _backend->busRegistry().findByIdentity(types::bus_kind_t::I2S, id)) {
            if (!BusTraits::configCompatible(static_cast<const IBusConfig&>(existing->getConfig()), cfg)) {
                return m5::stl::make_unexpected(error::error_t::INVALID_STATE);
            }
        }
        auto acquired = _backend->busRegistry().acquireOrFind(
            types::bus_kind_t::I2S, id, [&cfg]() -> result_t<std::shared_ptr<bus::IBus>> {
                std::shared_ptr<Bus> facade{new (std::nothrow) Bus()};
                if (!facade) {
                    return m5::stl::make_unexpected(error::error_t::OUT_OF_RESOURCE);
                }
                auto r = facade->init(cfg);
                if (!r.has_value()) {
                    return m5::stl::make_unexpected(r.error());
                }
                return std::shared_ptr<bus::IBus>{facade};
            });
        if (!acquired.has_value()) {
            return m5::stl::make_unexpected(acquired.error());
        }
        return std::static_pointer_cast<IBus>(acquired.value());
    }

    result_t<std::shared_ptr<IBus>> acquire(const LogicalBusConfig& req)
    {
        if (_backend == nullptr) {
            return m5::stl::make_unexpected(error::error_t::NOT_CONNECTED);
        }
        bus::IdentityKey id = BusTraits::identityFromLogical(req);
        if (!id.valid()) {
            return m5::stl::make_unexpected(error::error_t::INVALID_ARGUMENT);
        }
        if (!req.intent.valid()) {
            return m5::stl::make_unexpected(error::error_t::INVALID_ARGUMENT);
        }
        bus::AllocationRequest ar{types::bus_kind_t::I2S, id, req.intent, &req};
        auto acquired = _backend->acquireBusLogical(types::bus_kind_t::I2S, id, ar);
        if (!acquired.has_value()) {
            return m5::stl::make_unexpected(acquired.error());
        }
        return std::static_pointer_cast<IBus>(acquired.value());
    }

    result_t<void> commitBuses(uint32_t timeout_ms = types::TIMEOUT_FOREVER)
    {
        if (_backend == nullptr) {
            return m5::stl::make_unexpected(error::error_t::NOT_CONNECTED);
        }
        return _backend->commitBuses(types::bus_kind_t::I2S, timeout_ms);
    }

    /*!
      @brief Explicitly release a bus acquired via acquire().

      Clears the registry slot for the bus so capacity is reclaimed
      immediately. For a remote backend this also sends BusRelease to
      the peer. Pass the `shared_ptr<IBus>` returned by acquire().
      Returns `INVALID_ARGUMENT` if the bus is null, its config pins
      are invalid, or no matching slot is found in the registry.
     */
    result_t<void> release(const std::shared_ptr<IBus>& bus)
    {
        if (_backend == nullptr || !bus) {
            return m5::stl::make_unexpected(error::error_t::INVALID_ARGUMENT);
        }
        bus::IdentityKey id = BusTraits::identityFromConfig(bus->getConfig());
        if (!id.valid()) {
            return m5::stl::make_unexpected(error::error_t::INVALID_ARGUMENT);
        }
        return _backend->releaseBus(types::bus_kind_t::I2S, id);
    }

    uint8_t hardwareInUse(void) const
    {
        return 0;
    }

    LogicalBusConfig createBusConfig(Bclk bclk, Ws ws, Dout dout, types::AllocationIntent intent = {}) const
    {
        return {bclk, ws, dout, intent};
    }
    LogicalBusConfig createBusConfig(Bclk bclk, Ws ws, Din din, types::AllocationIntent intent = {}) const
    {
        return {bclk, ws, din, intent};
    }
    LogicalBusConfig createBusConfig(Bclk bclk, Ws ws, Dout dout, Din din, types::AllocationIntent intent = {}) const
    {
        return {bclk, ws, dout, din, intent};
    }

private:
    bus::IHalBackend* _backend;
};

/*!
  @brief Non-owning I2S bus group; retained for code that uses the
         slot-based publish/lookup table directly.
 */
using BusGroup = bus::BusGroup<IBus>;

}  // namespace m5::hal::v2::i2s

#endif
