// SPDX-License-Identifier: MIT
// Expected compile failure. The runner supplies one M5HAL_TEST_VARIANT_KIND_*
// selector and M5HAL_TEST_VARIANT_ID (unknown, unavailable, or non-offering).
#ifndef M5HAL_TEST_VARIANT_ID
#error "build_check_variant_rejected.cpp requires M5HAL_TEST_VARIANT_ID"
#endif

#if defined(M5HAL_TEST_VARIANT_KIND_RUNTIME)
#define M5HAL_CONFIG_VARIANT_RUNTIME M5HAL_TEST_VARIANT_ID
#elif defined(M5HAL_TEST_VARIANT_KIND_RUNTIME_MUTEX)
#define M5HAL_CONFIG_VARIANT_RUNTIME_MUTEX M5HAL_TEST_VARIANT_ID
#elif defined(M5HAL_TEST_VARIANT_KIND_RUNTIME_TASK)
#define M5HAL_CONFIG_VARIANT_RUNTIME_TASK M5HAL_TEST_VARIANT_ID
#elif defined(M5HAL_TEST_VARIANT_KIND_RUNTIME_EVENT)
#define M5HAL_CONFIG_VARIANT_RUNTIME_EVENT M5HAL_TEST_VARIANT_ID
#elif defined(M5HAL_TEST_VARIANT_KIND_GPIO)
#define M5HAL_CONFIG_VARIANT_GPIO M5HAL_TEST_VARIANT_ID
#elif defined(M5HAL_TEST_VARIANT_KIND_I2C)
#define M5HAL_CONFIG_VARIANT_I2C M5HAL_TEST_VARIANT_ID
#elif defined(M5HAL_TEST_VARIANT_KIND_SPI)
#define M5HAL_CONFIG_VARIANT_SPI M5HAL_TEST_VARIANT_ID
#elif defined(M5HAL_TEST_VARIANT_KIND_I2S)
#define M5HAL_CONFIG_VARIANT_I2S M5HAL_TEST_VARIANT_ID
#elif defined(M5HAL_TEST_VARIANT_KIND_PDM)
#define M5HAL_CONFIG_VARIANT_PDM M5HAL_TEST_VARIANT_ID
#elif defined(M5HAL_TEST_VARIANT_KIND_UART)
#define M5HAL_CONFIG_VARIANT_UART M5HAL_TEST_VARIANT_ID
#else
#error "build_check_variant_rejected.cpp requires one M5HAL_TEST_VARIANT_KIND_* selector"
#endif

#include <M5HAL_v2.hpp>
